package com.unl.music.base.models;

public enum RolArtistaEnum {
    SOLISTA, VOCALISTA ,BATERISTA, BAJISTA, GUITARRISTA, TECLADISTA, SAXOFONISTA, TRUMPETISTA, PERCUSIONISTA, BAJO_SEXTO, VIOLINISTA, VIOLONCELISTA, CHELISTA, ARPAISTAS, FLAUTISTA, CLARINETISTA, TROMBONISTA, TROMPETISTA, PIANISTA, ACORDEONISTA;
    
}
